MODEL: Salesforce/instructblip-flan-t5-xxl
TEMPERATURE: 0.
MAX_TOKENS: 8
SLEEP_PER_INFER: 10

PROMPT_HEAD: "Please choose the correct answer in the choices according to the context, the image tagging information, the question, the answer candidates. Each answer candidate is associated with a confidence score within a bracket. The true answer may not be included in the candidates. The image tagging information follows the format: object(confidence): [x_min, x_max, y_min, y_max].\n\n"
LINE_PREFIX: "===\n"
N_EXAMPLES: 20
K_CANDIDATES: 10
T_INFER: 5